/**
 * YouTube 字幕軌取得（獨立隔離模組）。
 *
 * ⚠️ 此模組依賴 YouTube 未公開的頁面結構，是整個外掛最容易因 YouTube 改版而失效的地方，
 *    因此所有「與 YouTube 內部結構相關」的邏輯都集中在這個檔案，方便日後修補。
 *
 * 取得方式（方案 A）：
 * 1. 在使用者的瀏覽器 session 內重新 fetch 目前影片的 watch 頁 HTML
 *    （content script 與 youtube.com 同源，此請求會自帶使用者的 cookies）
 * 2. 從 HTML 中抽出 ytInitialPlayerResponse JSON
 * 3. 讀取 captions.playerCaptionsTracklistRenderer.captionTracks 取得字幕軌清單
 * 4. 以字幕軌的 baseUrl 加上 fmt=json3 取回逐句字幕；失敗時退回解析 XML 格式
 *
 * 之所以「重新 fetch」而不直接讀 window.ytInitialPlayerResponse：
 * - content script 位於隔離世界，讀不到頁面的全域變數
 * - SPA 換片後頁面內嵌的初始資料是舊影片的，重新抓才會是目前影片
 */

/** 一條字幕軌的資訊 */
export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  /** 顯示名稱，例如「中文（繁體）」或「英文（自動產生）」 */
  displayName: string;
  /** 是否為自動產生（ASR）字幕 */
  isAutoGenerated: boolean;
}

/** 一句字幕（時間單位：秒） */
export interface SubtitleCue {
  start: number;
  end: number;
  text: string;
}

/** ytInitialPlayerResponse 中我們會用到的結構 */
interface PlayerResponse {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: Array<{
        baseUrl?: string;
        languageCode?: string;
        name?: { simpleText?: string; runs?: Array<{ text?: string }> };
        kind?: string; // 'asr' = 自動產生
      }>;
    };
  };
}

/**
 * 從 HTML 原始碼中抽出 ytInitialPlayerResponse 的 JSON 字串。
 * 不用 regex 抓整段（JSON 內含大括號會誤判），改用「括號配對掃描」：
 * 從第一個 '{' 開始逐字元掃描，追蹤字串與跳脫狀態，直到括號深度歸零。
 */
function extractPlayerResponseJson(html: string): string | null {
  const marker = 'ytInitialPlayerResponse';
  const markerIndex = html.indexOf(marker);
  if (markerIndex === -1) return null;

  const start = html.indexOf('{', markerIndex);
  if (start === -1) return null;

  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let i = start; i < html.length; i++) {
    const ch = html[i];
    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (ch === '\\') {
        escaped = true;
      } else if (ch === '"') {
        inString = false;
      }
    } else if (ch === '"') {
      inString = true;
    } else if (ch === '{') {
      depth++;
    } else if (ch === '}') {
      depth--;
      if (depth === 0) {
        return html.slice(start, i + 1);
      }
    }
  }
  return null;
}

/** 取得指定影片的字幕軌清單；影片沒有字幕時回傳空陣列 */
export async function fetchCaptionTracks(videoId: string): Promise<CaptionTrack[]> {
  const response = await fetch(`https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}`, {
    credentials: 'include',
  });
  if (!response.ok) {
    throw new Error(`無法載入影片頁面（HTTP ${response.status}）`);
  }

  const html = await response.text();
  const json = extractPlayerResponseJson(html);
  if (!json) {
    throw new Error('找不到 ytInitialPlayerResponse，YouTube 頁面結構可能已改版');
  }

  let playerResponse: PlayerResponse;
  try {
    playerResponse = JSON.parse(json) as PlayerResponse;
  } catch {
    throw new Error('ytInitialPlayerResponse 解析失敗，YouTube 頁面結構可能已改版');
  }

  const rawTracks = playerResponse.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  return rawTracks
    .filter((track) => typeof track.baseUrl === 'string')
    .map((track) => ({
      baseUrl: track.baseUrl!,
      languageCode: track.languageCode ?? '',
      displayName:
        track.name?.simpleText ??
        track.name?.runs?.map((run) => run.text ?? '').join('') ??
        track.languageCode ??
        '未知語言',
      isAutoGenerated: track.kind === 'asr',
    }));
}

/** json3 格式的事件結構 */
interface Json3Event {
  tStartMs?: number;
  dDurationMs?: number;
  /** aAppend=1 的事件是前一句的「接續片段」，直接顯示會造成重複 */
  aAppend?: number;
  segs?: Array<{ utf8?: string }>;
}

/** 取回並解析一條字幕軌的所有字幕句 */
export async function fetchCues(track: CaptionTrack): Promise<SubtitleCue[]> {
  // 優先使用 json3 格式（結構化、含毫秒時間軸）
  const response = await fetch(`${track.baseUrl}&fmt=json3`, { credentials: 'include' });
  if (!response.ok) {
    throw new Error(`字幕下載失敗（HTTP ${response.status}），字幕網址可能已過期`);
  }

  const body = await response.text();
  try {
    return parseJson3(body);
  } catch {
    // json3 解析失敗 → 退回 XML timedtext 格式
    return parseTimedTextXml(body);
  }
}

function parseJson3(body: string): SubtitleCue[] {
  const data = JSON.parse(body) as { events?: Json3Event[] };
  if (!Array.isArray(data.events)) {
    throw new Error('非 json3 格式');
  }

  const cues: SubtitleCue[] = [];
  for (const event of data.events) {
    if (event.aAppend === 1) continue; // 跳過接續片段，避免重複
    if (typeof event.tStartMs !== 'number' || !event.segs) continue;

    const text = event.segs
      .map((seg) => seg.utf8 ?? '')
      .join('')
      .replace(/\n/g, ' ')
      .trim();
    if (!text) continue;

    cues.push({
      start: event.tStartMs / 1000,
      end: (event.tStartMs + (event.dDurationMs ?? 2000)) / 1000,
      text,
    });
  }
  return cues;
}

/** 解析舊式 XML 格式：<text start="1.2" dur="3.4">內容</text> */
function parseTimedTextXml(body: string): SubtitleCue[] {
  const doc = new DOMParser().parseFromString(body, 'text/xml');
  const nodes = doc.querySelectorAll('text');
  if (nodes.length === 0) {
    throw new Error('字幕格式無法解析（json3 與 XML 皆失敗），YouTube 可能已改版');
  }

  const cues: SubtitleCue[] = [];
  for (const node of nodes) {
    const start = parseFloat(node.getAttribute('start') ?? '');
    const duration = parseFloat(node.getAttribute('dur') ?? '2');
    const text = (node.textContent ?? '').replace(/\s+/g, ' ').trim();
    if (Number.isNaN(start) || !text) continue;
    cues.push({ start, end: start + duration, text });
  }
  return cues;
}
