/**
 * YouTube 字幕軌取得（獨立隔離模組）。
 *
 * ⚠️ 此模組依賴 YouTube 未公開的頁面結構，是整個外掛最容易因 YouTube 改版而失效的地方，
 *    因此所有「與 YouTube 內部結構相關」的邏輯都集中在這個檔案，方便日後修補。
 *
 * 取得方式（方案 A）：
 * 1. 在使用者的瀏覽器 session 內重新 fetch 目前影片的 watch 頁 HTML
 *    （content script 與 youtube.com 同源，此請求會自帶使用者的 cookies）
 * 2. 從 HTML 中抽出 ytInitialPlayerResponse JSON
 * 3. 讀取 captions.playerCaptionsTracklistRenderer.captionTracks 取得字幕軌清單
 * 4. 以字幕軌的 baseUrl 取回逐句字幕：依序嘗試 fmt=json3 → fmt=srv3 → 預設 XML
 *    （帶 variant 參數時另以去除 variant 的 URL 重試一輪）；YouTube 缺授權時
 *    會回 200 空 body 而非 4xx，空回應視為「拿不到內容」而非格式錯誤
 * 5. 第 4 步全部落空時，走 InnerTube（youtubei/v1/player，ANDROID client）
 *    重新取得「不需 pot token」的 baseUrl 再試一輪（詳見 fetchTracksViaInnerTube 註解）
 *
 * 之所以「重新 fetch」而不直接讀 window.ytInitialPlayerResponse：
 * - content script 位於隔離世界，讀不到頁面的全域變數
 * - SPA 換片後頁面內嵌的初始資料是舊影片的，重新抓才會是目前影片
 */

/** 一條字幕軌的資訊 */
export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  /** 顯示名稱，例如「中文（繁體）」或「英文（自動產生）」 */
  displayName: string;
  /** 是否為自動產生（ASR）字幕 */
  isAutoGenerated: boolean;
  /** 所屬影片 ID（fetchCues 走 InnerTube 備援時需要重新要字幕軌） */
  videoId: string;
}

/** 一句字幕（時間單位：秒） */
export interface SubtitleCue {
  start: number;
  end: number;
  text: string;
}

/** ytInitialPlayerResponse 中我們會用到的結構 */
interface PlayerResponse {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: Array<{
        baseUrl?: string;
        languageCode?: string;
        name?: { simpleText?: string; runs?: Array<{ text?: string }> };
        kind?: string; // 'asr' = 自動產生
      }>;
    };
  };
}

/**
 * 從 HTML 原始碼中抽出 ytInitialPlayerResponse 的 JSON 字串。
 * 不用 regex 抓整段（JSON 內含大括號會誤判），改用「括號配對掃描」：
 * 從第一個 '{' 開始逐字元掃描，追蹤字串與跳脫狀態，直到括號深度歸零。
 */
function extractPlayerResponseJson(html: string): string | null {
  const marker = 'ytInitialPlayerResponse';
  const markerIndex = html.indexOf(marker);
  if (markerIndex === -1) return null;

  const start = html.indexOf('{', markerIndex);
  if (start === -1) return null;

  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let i = start; i < html.length; i++) {
    const ch = html[i];
    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (ch === '\\') {
        escaped = true;
      } else if (ch === '"') {
        inString = false;
      }
    } else if (ch === '"') {
      inString = true;
    } else if (ch === '{') {
      depth++;
    } else if (ch === '}') {
      depth--;
      if (depth === 0) {
        return html.slice(start, i + 1);
      }
    }
  }
  return null;
}

/** 取得指定影片的字幕軌清單；影片沒有字幕時回傳空陣列 */
export async function fetchCaptionTracks(videoId: string): Promise<CaptionTrack[]> {
  const response = await fetch(`https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}`, {
    credentials: 'include',
  });
  if (!response.ok) {
    throw new Error(`無法載入影片頁面（HTTP ${response.status}）`);
  }

  const html = await response.text();
  const json = extractPlayerResponseJson(html);
  if (!json) {
    throw new Error('找不到 ytInitialPlayerResponse，YouTube 頁面結構可能已改版');
  }

  let playerResponse: PlayerResponse;
  try {
    playerResponse = JSON.parse(json) as PlayerResponse;
  } catch {
    throw new Error('ytInitialPlayerResponse 解析失敗，YouTube 頁面結構可能已改版');
  }

  return mapCaptionTracks(playerResponse, videoId);
}

/** 把 playerResponse 的 captionTracks 整理成 CaptionTrack（watch 頁與 InnerTube 回應結構相同） */
function mapCaptionTracks(playerResponse: PlayerResponse, videoId: string): CaptionTrack[] {
  const rawTracks = playerResponse.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  return rawTracks
    .filter((track) => typeof track.baseUrl === 'string')
    .map((track) => ({
      baseUrl: track.baseUrl!,
      languageCode: track.languageCode ?? '',
      displayName:
        track.name?.simpleText ??
        track.name?.runs?.map((run) => run.text ?? '').join('') ??
        track.languageCode ??
        '未知語言',
      isAutoGenerated: track.kind === 'asr',
      videoId,
    }));
}

/**
 * InnerTube 備援：以 ANDROID client 向 youtubei/v1/player 重新要字幕軌。
 *
 * 背景（2026-07-13 spike 實證，過程見計畫附錄）：YouTube 對 timedtext 端點要求
 * pot（proof-of-origin token），watch 頁 HTML 內的 baseUrl 沒有 pot，fetch 一律
 * 回 200 空 body；但 ANDROID／IOS client 經 InnerTube 拿到的 baseUrl 不需 pot
 * 即可取得內容（WEB client 則直接不回字幕軌）。此路徑屬 YouTube 未公開行為，
 * 失效時優先檢查 clientName／clientVersion 是否仍被接受。
 * 注意：`?key=` 參數已非必要，省略即可（content script 讀不到頁面的 ytcfg）。
 */
async function fetchTracksViaInnerTube(videoId: string): Promise<CaptionTrack[]> {
  const response = await fetch('https://www.youtube.com/youtubei/v1/player', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      context: {
        client: { clientName: 'ANDROID', clientVersion: '20.10.38', androidSdkVersion: 30, hl: 'en' },
      },
      videoId,
    }),
    credentials: 'include',
  });
  if (!response.ok) {
    throw new Error(`InnerTube 請求失敗（HTTP ${response.status}）`);
  }
  const playerResponse = (await response.json()) as PlayerResponse;
  return mapCaptionTracks(playerResponse, videoId);
}

/** json3 格式的事件結構 */
interface Json3Event {
  tStartMs?: number;
  dDurationMs?: number;
  /** aAppend=1 的事件是前一句的「接續片段」，直接顯示會造成重複 */
  aAppend?: number;
  segs?: Array<{ utf8?: string }>;
}

/**
 * 取回並解析一條字幕軌的所有字幕句。
 *
 * ⚠️ YouTube 在授權條件不符（如缺 pot token）時會回 HTTP 200 但 body 為空，
 *    而非 4xx，因此不能把回應直接丟進解析器。這裡依序嘗試候選 URL
 *    （fmt=json3 → fmt=srv3 → 預設 XML；baseUrl 帶 variant 參數時，再以
 *    去除 variant 的 URL 重試一輪），空回應就換下一個，全部失敗才拋錯，
 *    並依失敗型態給出對應錯誤訊息（空內容／非預期內容／格式解析失敗）。
 */
export async function fetchCues(track: CaptionTrack): Promise<SubtitleCue[]> {
  let firstError: Error;
  try {
    return await fetchCuesFromBaseUrl(track.baseUrl);
  } catch (err) {
    firstError = err instanceof Error ? err : new Error(String(err));
  }

  // 第一輪全落空（最常見原因：baseUrl 缺 pot token，YouTube 回 200 空 body）
  // → 走 InnerTube 備援要一份不需 pot 的 baseUrl 再試一輪
  try {
    const freshTrack = (await fetchTracksViaInnerTube(track.videoId)).find(
      (t) => t.languageCode === track.languageCode && t.isAutoGenerated === track.isAutoGenerated,
    );
    if (!freshTrack) throw firstError;
    return await fetchCuesFromBaseUrl(freshTrack.baseUrl);
  } catch {
    // 備援也失敗：拋第一輪的分類錯誤（對使用者較準確，備援的失敗細節屬內部實作）
    throw firstError;
  }
}

/** 對單一 baseUrl 依序嘗試所有候選格式；全部落空時拋出分類過的錯誤 */
async function fetchCuesFromBaseUrl(baseUrl: string): Promise<SubtitleCue[]> {
  let sawEmptyBody = false;
  let lastError: Error | null = null;

  for (const url of buildCandidateUrls(baseUrl)) {
    let body: string;
    try {
      const response = await fetch(url, { credentials: 'include' });
      if (!response.ok) {
        lastError = new Error(`字幕下載失敗（HTTP ${response.status}），字幕網址可能已過期`);
        continue;
      }
      body = (await response.text()).trim();
    } catch (err) {
      lastError = err instanceof Error ? err : new Error(String(err));
      continue;
    }

    if (!body) {
      sawEmptyBody = true;
      continue;
    }

    try {
      if (body.startsWith('{')) return parseJson3(body);
      if (body.startsWith('<')) return parseTimedTextXml(body);
      lastError = new Error('字幕來源回傳非預期內容（非 JSON 也非 XML），YouTube 可能已改版');
    } catch (err) {
      lastError = err instanceof Error ? err : new Error(String(err));
    }
  }

  if (lastError) throw lastError;
  throw new Error(
    sawEmptyBody
      ? '字幕來源回傳空內容——YouTube 未提供此字幕軌的資料（可能為暫時性限制），請重新整理頁面後再試'
      : '字幕下載失敗：沒有可用的字幕網址',
  );
}

/**
 * 依序產生候選字幕 URL：三種格式 ×（原始 baseUrl、去除 variant 的 baseUrl）。
 * - fmt 一律用 URL API「設定」而非字串附加：InnerTube 給的 baseUrl 可能已含
 *   fmt 參數，重複附加時伺服器只認第一個，設定才能真正切換格式
 * - variant（如 variant=gemini）是近期新出現的參數，去除後有機會取得內容，
 *   故列為第二輪重試
 */
function buildCandidateUrls(baseUrl: string): string[] {
  let parsed: URL;
  try {
    parsed = new URL(baseUrl, 'https://www.youtube.com');
  } catch {
    // baseUrl 不是合法 URL：退回舊式字串附加，至少維持基本嘗試
    return [`${baseUrl}&fmt=json3`, `${baseUrl}&fmt=srv3`, baseUrl];
  }

  const bases = [parsed];
  if (parsed.searchParams.has('variant')) {
    const stripped = new URL(parsed);
    stripped.searchParams.delete('variant');
    bases.push(stripped);
  }

  const formats: Array<string | null> = ['json3', 'srv3', null];
  const urls: string[] = [];
  for (const base of bases) {
    for (const fmt of formats) {
      const url = new URL(base);
      if (fmt) url.searchParams.set('fmt', fmt);
      else url.searchParams.delete('fmt');
      if (!urls.includes(url.toString())) urls.push(url.toString());
    }
  }
  return urls;
}

function parseJson3(body: string): SubtitleCue[] {
  const data = JSON.parse(body) as { events?: Json3Event[] };
  if (!Array.isArray(data.events)) {
    throw new Error('非 json3 格式');
  }

  const cues: SubtitleCue[] = [];
  for (const event of data.events) {
    if (event.aAppend === 1) continue; // 跳過接續片段，避免重複
    if (typeof event.tStartMs !== 'number' || !event.segs) continue;

    const text = event.segs
      .map((seg) => seg.utf8 ?? '')
      .join('')
      .replace(/\n/g, ' ')
      .trim();
    if (!text) continue;

    cues.push({
      start: event.tStartMs / 1000,
      end: (event.tStartMs + (event.dDurationMs ?? 2000)) / 1000,
      text,
    });
  }
  return cues;
}

/**
 * 解析 XML timedtext，支援兩種變體：
 * - 舊式（srv1／預設）：<text start="1.2" dur="3.4">內容</text>（時間單位：秒）
 * - srv3：<p t="1200" d="3400">內容</p>（時間單位：毫秒；a="1" 為前句的接續片段）
 */
function parseTimedTextXml(body: string): SubtitleCue[] {
  const doc = new DOMParser().parseFromString(body, 'text/xml');
  const cues: SubtitleCue[] = [];

  const srv1Nodes = doc.querySelectorAll('text');
  if (srv1Nodes.length > 0) {
    for (const node of srv1Nodes) {
      const start = parseFloat(node.getAttribute('start') ?? '');
      const duration = parseFloat(node.getAttribute('dur') ?? '2');
      const text = (node.textContent ?? '').replace(/\s+/g, ' ').trim();
      if (Number.isNaN(start) || !text) continue;
      cues.push({ start, end: start + duration, text });
    }
    return cues;
  }

  const srv3Nodes = doc.querySelectorAll('p[t]');
  if (srv3Nodes.length > 0) {
    for (const node of srv3Nodes) {
      if (node.getAttribute('a') === '1') continue; // 跳過接續片段，避免重複
      const startMs = parseFloat(node.getAttribute('t') ?? '');
      const durationMs = parseFloat(node.getAttribute('d') ?? '2000');
      const text = (node.textContent ?? '').replace(/\s+/g, ' ').trim();
      if (Number.isNaN(startMs) || !text) continue;
      cues.push({ start: startMs / 1000, end: (startMs + durationMs) / 1000, text });
    }
    return cues;
  }

  throw new Error('字幕格式無法解析（json3、srv3 與 XML 皆失敗），YouTube 可能已改版');
}
